import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] });
import 'tailwindcss/tailwind.css';
import Sidebar from '@/components/sidebar';
import { RecoilRoot } from 'recoil';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <div className='flex w-screen'>
          <Sidebar />
          <div className='flex-1'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
